name: 'Trigger Repository Dispatch'
description: 'Triggers a repository_dispatch to another repository'
inputs:
  personal_access_token:
    description: 'Personal Access Token with required permissions'
    required: true
  target_repo:
    description: 'The repository to trigger the dispatch on'
    required: true
  event_type:
    description: 'The event type to trigger'
    required: true
  client_payload:
    description: 'Client-specific payload'
    required: false
runs:
  using: 'composite'  # Updated to 'composite' for script execution
  steps:
    - name: Trigger repository_dispatch to target repository
      shell: bash  # Specify the shell here
      run: |
        RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.personal_access_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ inputs.target_repo }}/dispatches \
          -d "{\"event_type\": \"${{ inputs.event_type }}\", \"client_payload\": ${client_payload}}")
        if [[ ! "$RESPONSE" =~ ^2 ]]; then
          echo "Error triggering repository dispatch, HTTP status code: $RESPONSE"
          exit 1
        fi

        echo "Successfully triggered repository dispatch."
