name: 'Trigger Repository Dispatch'
description: 'Trigger a repository_dispatch event on another repository'
runs:
  using: "composite"
  steps:
    - name: Trigger repository_dispatch to test2-repo
      run: |
        echo "Triggering repository_dispatch to test2-repo"
        
        # Perform the curl call to trigger repository_dispatch, capture both output and status code
        RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gezimhasani/test2-repo/dispatches \
          -d '{"event_type": "test-event", "client_payload": {"unit": false, "integration": true}}')

        # Check if the HTTP status code starts with 2 (successful responses in the 2xx range)
        if [[ ! "$RESPONSE" =~ ^2 ]]; then
          echo "Error triggering repository dispatch, HTTP status code: $RESPONSE"
          exit 1  # Exit with error code to stop further steps
        fi
        
        echo "Successfully triggered repository dispatch."