name: Trigger Repository Dispatch to test-repo2

on:
  push:
    branches:
      - master  # Trigger this workflow when code is pushed to the 'master' branch

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checkout the code of the current repository

      - name: Trigger repository_dispatch to test-repo2
        run: |
          echo "Triggering repository_dispatch to test-repo2"
          curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/PureDiscovery/test-repo2/dispatches \
            -d '{"event_type": "test-event", "client_payload": {"unit": false, "integration": true}}'

