name: Sync Action Status Between Repos

on:
  push:
    branches:
      - master

jobs:
  sync-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt  # Install any required dependencies for your script

    - name: Run Python script to sync status
      run: |
        python scripts/sync_action_status.py \
          --current_repo "${{ github.repository }}" \
          --target_repo "gezimhasani/test2-repo" \
          --event_type "test-event" \
          --interval 60
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Make sure GH_TOKEN is stored in GitHub secrets
