name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger repository dispatch event
      uses: ./.github/actions/trigger-repo-dispatch
      with:
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        target_repo: 'gezimhasani/test2-repo'
        event_type: 'test-event'
        #client_payload: '{"unit": false, "integration": true}'
