name: Trigger Repository Dispatch to test2-repo

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
      ######
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checkout the code of the current repository

      - name: Trigger repository_dispatch to test2-repo
        id: trigger_dispatch
        continue-on-error: false
        run: |
          echo "Triggering repository_dispatch to test2-repo"
          curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gezimhasani/test2-repo/dispatches \
            -d '{"event_type": "test-event", "client_payload": {"unit": false, "integration": true}}'

