name: Trigger Repository Dispatch to test2-repo

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checkout the code of the current repository

      - name: Trigger repository_dispatch using custom action
        uses: ./.github/actions/trigger-repo-dispatch  # Calling the custom action we just created
