name: Trigger Repository Dispatch to test2-repo

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Trigger repository_dispatch to test2-repo
        uses: ./.github/actions/trigger-repo-dispatch
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          target_repo: "gezimhasani/test2-repo"
          event_type: "test-event"
          client_payload: '{"unit": false, "integration": true}'
