name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Trigger repository dispatch event for multiple repositories
        uses: philipdelorenzo/sync-action-status@v0.1.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          event_type: test-event
          current_repo: ${{ github.repository }}
          target_repo: "gezimhasani/test2-repo"
          debug: ${{ github.event.inputs.debug }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Set GH_TOKEN explicitly
